# -*- mode: ruby -*-
# vi: set ft=ruby :

$last_ip_digit = 9

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"

  config.vm.provider :libvirt do |lv|
    lv.cpu_mode = 'host-passthrough'
    lv.volume_cache = 'unsafe'
    lv.graphics_type = 'none'
    lv.cpus = 2
    lv.memory = 2048
    lv.storage :file, :device => "hdd", :size => '200G', :bus => "ide"
    driverletters = ('a'..'z').to_a
    (0..2).each do |d|
      lv.storage :file, :device => "hd#{driverletters[d]}", :size => '200G', :bus => "ide"
    end
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true

  (0..2).each do |i|
    config.vm.define "ceph-node-#{i}" do |node|
      node.vm.hostname = "ceph-node-#{i}"
      
      node.vm.network :private_network,
        ip: "192.168.100.#{$last_ip_digit+=1}"
      node.vm.network :private_network,
        ip: "192.168.200.#{$last_ip_digit+=1}"
    end
  end

  config.vm.provision "shell" do |s|
    s.inline = 'dnf -y install lvm2 podman'
  end
end

